In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("cleaned_parking.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (3309, 5)

   bay_id                  timestamp   latitude   longitude  occupancy
0   51614  2025-03-25 00:09:20+00:00 -37.816205  144.969789          0
1   17954  2025-03-24 23:56:53+00:00 -37.810200  144.972946          1
2   62710  2025-03-25 00:06:47+00:00 -37.813134  144.970672          0
3   51613  2025-03-24 23:16:22+00:00 -37.816253  144.969811          1
4   61835  2025-01-14 22:21:10+00:00 -37.814241  144.971091          1

In [10]:
def assign_area_by_bay(df):
    df = df.copy()

    areas = [
        "Richmond",
        "South Yarra",
        "Melbourne CBD",
        "Docklands",
        "Carlton",
        "Fitzroy",
        "St Kilda",
        "Brunswick"
    ]

    # Get unique parking bays
    unique_bays = sorted(df["bay_id"].unique())

    print("Number of unique parking bays:", len(unique_bays))

    # Map each bay_id to an area
    bay_to_area = {
        bay: areas[i % len(areas)]
        for i, bay in enumerate(unique_bays)
    }

    # Create new area column
    df["area"] = df["bay_id"].map(bay_to_area)

    return df

In [11]:
df = assign_area_by_bay(df)

print("Area counts:")
print(df["area"].value_counts())

df.head()

Number of unique parking bays: 3309
Area counts:
area
Richmond         414
Carlton          414
South Yarra      414
Docklands        414
Melbourne CBD    414
Brunswick        413
Fitzroy          413
St Kilda         413
Name: count, dtype: int64

,bay_id,timestamp,latitude,longitude,occupancy,area
0,51614,2025-03-25 00:09:20+00:00,-37.816205,144.969789,0,Fitzroy
1,17954,2025-03-24 23:56:53+00:00,-37.810200,144.972946,1,Fitzroy
2,62710,2025-03-25 00:06:47+00:00,-37.813134,144.970672,0,Brunswick
3,51613,2025-03-24 23:16:22+00:00,-37.816253,144.969811,1,Carlton
4,61835,2025-01-14 22:21:10+00:00,-37.814241,144.971091,1,Richmond

In [12]:
output_file = "cleaned_parking_with_area.csv"
df.to_csv(output_file, index=False)

print(f"Updated dataset saved as: {output_file}")

Updated dataset saved as: cleaned_parking_with_area.csv

In [13]:
saved_df = pd.read_csv("cleaned_parking_with_area.csv")
saved_df[["bay_id", "area"]].head(20)

    bay_id           area
0    51614        Fitzroy
1    17954        Fitzroy
2    62710      Brunswick
3    51613        Carlton
4    61835       Richmond
5    18076        Fitzroy
6    17956      Brunswick
7    69979      Docklands
8    10286        Carlton
9    10288       St Kilda
10   24423       St Kilda
11    9340    South Yarra
12    9354      Docklands
13   61147       St Kilda
14   56622        Carlton
15   21741      Docklands
16    9338       Richmond
17    9341  Melbourne CBD
18    9358      Brunswick
19    9357       St Kilda